### ISSUE TITLE
BUG: Sync block Error [org.rocksdb.RocksDBException:  Function not implemented]

### ISSUE THREAD

**Issue by suyanlong** [alephium/alephium#453]
- Blockchain env
```shell
mainnet
```
- Linux env: 
```shell
root@DESKTOP-0QIGCLU:~/alephium/alephium# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```
- Run command: 
```shell
java -jar -Xmx500m alephium-1.1.7.jar # first run
```

- alephium-1.1.7.jar from make assembly on master

- Run log 
```shell
2021-12-09 09:34:31,032 [-dispatcher-4] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000006b677219832f36a46abebed12a5125c4ea60bffada2437e6db2b76b; ChainIndex(2, 3); height: 242/242; total: 4038; target hashrate: 549761 MH/s, blockTime: 119679ms #tx: 1
2021-12-09 09:34:31,032 [dispatcher-10] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000007f785f919cbf25aa4954d4ca3118eb0e3a2573e384e1d4fda19ceb8; ChainIndex(2, 0); height: 271/271; total: 4040; target hashrate: 549761 MH/s, blockTime: 305748ms #tx: 1
2021-12-09 09:34:31,032 [-dispatcher-9] INFO  o.a.f.h.BlockChainHandler              - hash: 000000000739d4a8fa9f82a23cfd91df15732e553fc21397fcf6df8f6f6f2dcd; ChainIndex(3, 1); height: 238/238; total: 4040; target hashrate: 549761 MH/s, blockTime: 107496ms #tx: 1
2021-12-09 09:34:31,032 [-dispatcher-9] INFO  o.a.f.h.BlockChainHandler              - fbe3e664 is validated
2021-12-09 09:34:31,033 [-dispatcher-9] INFO  o.a.f.h.BlockChainHandler              - 3f0aa736 is validated
2021-12-09 09:34:31,033 [dispatcher-13] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000000b5face087c5e054e704887b7e503338f52b278b17371f8fbe3e664; ChainIndex(1, 0); height: 262/262; total: 4041; target hashrate: 549761 MH/s, blockTime: 230377ms #tx: 1
2021-12-09 09:34:31,033 [dispatcher-13] INFO  o.a.f.h.BlockChainHandler              - c5ec08b8 is validated
2021-12-09 09:34:31,033 [dispatcher-13] INFO  o.a.f.h.BlockChainHandler              - 1a00076d is validated
2021-12-09 09:34:31,033 [dispatcher-16] INFO  o.a.f.h.BlockChainHandler              - hash: 000000000754080c71b421678175d0872d9ffff87a5e28c3b889ac713f0aa736; ChainIndex(1, 2); height: 244/244; total: 4042; target hashrate: 549761 MH/s, blockTime: 13614ms #tx: 1
2021-12-09 09:34:31,033 [-dispatcher-8] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000006865aae815ea3e56b27f9c71f54eaa3f214729a97fff94cc5ec08b8; ChainIndex(2, 0); height: 272/272; total: 4043; target hashrate: 549761 MH/s, blockTime: 20097ms #tx: 1
2021-12-09 09:34:31,034 [-dispatcher-6] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000007f47e2018ee73105f62beec32677dac4dba271fbc031aad1a00076d; ChainIndex(3, 1); height: 239/239; total: 4044; target hashrate: 549761 MH/s, blockTime: 18944ms #tx: 1
2021-12-09 09:34:31,034 [-dispatcher-6] INFO  o.a.f.h.BlockChainHandler              - b2fc6115 is validated
2021-12-09 09:34:31,034 [-dispatcher-6] INFO  o.a.f.h.BlockChainHandler              - b46dd8f9 is validated
2021-12-09 09:34:31,034 [-dispatcher-6] INFO  o.a.f.h.BlockChainHandler              - 35e341fd is validated
2021-12-09 09:34:31,034 [-dispatcher-7] INFO  o.a.f.h.BlockChainHandler              - hash: 00000000048a824528a5deb481720f911968aead099c712b0adca93fb46dd8f9; ChainIndex(2, 1); height: 248/248; total: 4045; target hashrate: 549761 MH/s, blockTime: 189220ms #tx: 1
2021-12-09 09:34:31,035 [-dispatcher-8] INFO  o.a.f.h.BlockChainHandler              - hash: 000000000069f702b89cc05cad5266fc648a04bb9c65869215769763b2fc6115; ChainIndex(1, 1); height: 237/237; total: 4046; target hashrate: 549761 MH/s, blockTime: 63861ms #tx: 1
2021-12-09 09:34:31,035 [dispatcher-14] INFO  o.a.f.h.BlockChainHandler              - hash: 00000000072c20d47e7cf12b7a140f02ee20d27c2eb6201506a9fcf935e341fd; ChainIndex(3, 1); height: 240/240; total: 4047; target hashrate: 549761 MH/s, blockTime: 21250ms #tx: 1
2021-12-09 09:34:31,035 [dispatcher-14] INFO  o.a.f.h.BlockChainHandler              - c3a6cd99 is validated
2021-12-09 09:34:31,035 [dispatcher-14] INFO  o.a.f.h.BlockChainHandler              - cb7204c4 is validated
2021-12-09 09:34:31,036 [-dispatcher-4] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000003487c756bea88056bce432992be9e7fbcb9dcc82980d9d4cb7204c4; ChainIndex(1, 0); height: 263/263; total: 4049; target hashrate: 549761 MH/s, blockTime: 30628ms #tx: 1
2021-12-09 09:34:31,036 [-dispatcher-4] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000005b827366451ee52feedc284b66beb57b6a4cab6568d5f23c3a6cd99; ChainIndex(2, 1); height: 249/249; total: 4049; target hashrate: 549761 MH/s, blockTime: 2490ms #tx: 1
2021-12-09 09:34:31,036 [-dispatcher-4] INFO  o.a.f.h.BlockChainHandler              - 98a356fd is validated
2021-12-09 09:34:31,037 [dispatcher-13] INFO  o.a.f.h.BlockChainHandler              - 4e8f430b is validated
2021-12-09 09:34:31,037 [dispatcher-13] INFO  o.a.f.h.BlockChainHandler              - 03472f95 is validated
2021-12-09 09:34:31,037 [dispatcher-13] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000003b4de1a63d4dbbc9c1f8beecb546012dfff497ea9e243d298a356fd; ChainIndex(3, 1); height: 241/241; total: 4050; target hashrate: 549761 MH/s, blockTime: 6066ms #tx: 1
2021-12-09 09:34:31,037 [dispatcher-13] INFO  o.a.f.h.BlockChainHandler              - acf925b7 is validated
2021-12-09 09:34:31,037 [dispatcher-13] INFO  o.a.f.h.BlockChainHandler              - 8f726198 is validated
2021-12-09 09:34:31,037 [dispatcher-12] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000004ccdee05c316e55355b7a633ff8a57d2190bbd7be19cbacacf925b7; ChainIndex(1, 3); height: 277/277; total: 4051; target hashrate: 549761 MH/s, blockTime: 165600ms #tx: 1
2021-12-09 09:34:31,038 [dispatcher-10] INFO  o.a.f.h.BlockChainHandler              - hash: 000000000391cb58f70d08690591aa1335c75badb440fd24673627f04e8f430b; ChainIndex(2, 3); height: 243/243; total: 4053; target hashrate: 549761 MH/s, blockTime: 65940ms #tx: 1
2021-12-09 09:34:31,038 [dispatcher-10] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000005d426ddf63dd9210992a562e7c805c53234cb252d5fd94f8f726198; ChainIndex(2, 0); height: 273/273; total: 4053; target hashrate: 549761 MH/s, blockTime: 73740ms #tx: 1
2021-12-09 09:34:31,038 [dispatcher-16] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000001a1c338a19c1b24724e0d42199fa30a0229ff0f2ec1955503472f95; ChainIndex(1, 1); height: 238/238; total: 4054; target hashrate: 549761 MH/s, blockTime: 41600ms #tx: 1
2021-12-09 09:34:31,039 [dispatcher-16] INFO  o.a.f.h.BlockChainHandler              - e16dadd4 is validated
2021-12-09 09:34:31,039 [dispatcher-16] INFO  o.a.f.h.BlockChainHandler              - 11a930bd is validated
2021-12-09 09:34:31,039 [dispatcher-16] INFO  o.a.f.h.BlockChainHandler              - f9f7bba1 is validated
2021-12-09 09:34:31,039 [dispatcher-16] INFO  o.a.f.h.BlockChainHandler              - b26a006a is validated
2021-12-09 09:34:31,039 [-dispatcher-6] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000003cc2f64e3a5e5d4d0b05c5adfe65054599939517b9dba29e16dadd4; ChainIndex(1, 0); height: 264/264; total: 4055; target hashrate: 549761 MH/s, blockTime: 36132ms #tx: 1
2021-12-09 09:34:31,039 [-dispatcher-9] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000007936a0836019687633621533d90f80dea0c43bcdfc94195f9f7bba1; ChainIndex(0, 1); height: 246/246; total: 4056; target hashrate: 549761 MH/s, blockTime: 245378ms #tx: 1
2021-12-09 09:34:31,039 [-dispatcher-9] INFO  o.a.f.h.BlockChainHandler              - hash: 000000000342f3db92ec1f46187589a7476b3179e69760831a55780411a930bd; ChainIndex(3, 1); height: 242/242; total: 4057; target hashrate: 549761 MH/s, blockTime: 80285ms #tx: 1
2021-12-09 09:34:31,040 [-dispatcher-9] INFO  o.a.f.h.BlockChainHandler              - 11e862d1 is validated
2021-12-09 09:34:31,040 [-dispatcher-9] INFO  o.a.f.h.BlockChainHandler              - ed0e9275 is validated
2021-12-09 09:34:31,040 [-dispatcher-5] INFO  o.a.f.h.BlockChainHandler              - hash: 000000000724d0bfc2cda1f2d48bd5f31c1505d02966b44fe241b1ca11e862d1; ChainIndex(0, 1); height: 247/247; total: 4058; target hashrate: 549761 MH/s, blockTime: 24326ms #tx: 1
2021-12-09 09:34:31,041 [-dispatcher-6] INFO  o.a.f.h.BlockChainHandler              - hash: 00000000041b335d72b7c280f4859bbdae3308277d4a1e4e508fa12ced0e9275; ChainIndex(1, 1); height: 239/239; total: 4059; target hashrate: 549761 MH/s, blockTime: 58629ms #tx: 1
2021-12-09 09:34:31,041 [-dispatcher-6] INFO  o.a.f.h.BlockChainHandler              - hash: 00000000054389a7b69270ca90f47b97c248b9e1d196131546abfe94b26a006a; ChainIndex(2, 2); height: 251/251; total: 4060; target hashrate: 549761 MH/s, blockTime: 429362ms #tx: 1
2021-12-09 09:34:31,042 [-dispatcher-6] INFO  o.a.f.h.BlockChainHandler              - 08f24586 is validated
2021-12-09 09:34:31,042 [-dispatcher-6] INFO  o.a.f.h.BlockChainHandler              - bec21372 is validated
2021-12-09 09:34:31,043 [-dispatcher-6] INFO  o.a.f.h.BlockChainHandler              - hash: 00000000065b3e18e88e7219ce8c4c18f050fe07efe7e5567b16315908f24586; ChainIndex(1, 2); height: 245/245; total: 4062; target hashrate: 549761 MH/s, blockTime: 150577ms #tx: 1
2021-12-09 09:34:31,043 [-dispatcher-6] INFO  o.a.f.h.BlockChainHandler              - hash: 0000000003bd697b1cb097d6dbab9129fdce512ec54ef4dc2433ef32bec21372; ChainIndex(0, 2); height: 230/230; total: 4062; target hashrate: 549761 MH/s, blockTime: 353268ms #tx: 1
2021-12-09 09:34:32,711 [-dispatcher-4] INFO  o.a.f.h.BlockChainHandler              - 6aeb0e38 is validated
2021-12-09 09:34:32,715 [dispatcher-16] ERROR o.a.f.h.BlockChainHandler              - IO failed: org.alephium.io.IOError$RocksDB: org.rocksdb.RocksDBException: While sync_file_range offset 0 bytes 2031616: /root/.alephium/mainnet/db/000029.sst: Function not implemented

```

- Error log infomation: 

**2021-12-09 09:34:32,715 [dispatcher-16] ERROR o.a.f.h.BlockChainHandler              - IO failed: org.alephium.io.IOError$RocksDB: org.rocksdb.RocksDBException: While sync_file_range offset 0 bytes 2031616: /root/.alephium/mainnet/db/000029.sst: Function not implemented**

- Code stack called print(second run):
```shell
root@DESKTOP-0QIGCLU:~/alephium# java -jar -Xmx500m alephium-1.1.7.jar
2021-12-09 09:58:25,656 [main]          INFO  o.a.f.s.Configs$                       - Using user configuration file at /root/.alephium/user.conf
2021-12-09 09:58:25,682 [main]          INFO  o.a.f.s.Configs$                       - Using system configuration file at /root/.alephium/mainnet/system.conf
2021-12-09 09:58:25,694 [main]          INFO  o.a.f.s.Configs$                       - Using network configuration file at /root/.alephium/mainnet/network.conf
2021-12-09 09:58:35,201 [-dispatcher-4] INFO  a.e.s.Slf4jLogger                      - Slf4jLogger started
2021-12-09 09:58:35,442 [main]          ERROR o.alephium.app.Boot$                   - Cannot initialize system: {}
org.rocksdb.RocksDBException: While sync_file_range offset 0 bytes 1957888: /root/.alephium/mainnet/db/000032.sst: Function not implemented
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:286)
	at org.alephium.io.RocksDBSource$.openUnsafeWithOptions(RocksDBSource.scala:171)
	at org.alephium.io.RocksDBSource$.openUnsafe(RocksDBSource.scala:151)
	at org.alephium.flow.io.Storages$.createRocksDBUnsafe(Storages.scala:71)
	at org.alephium.flow.io.Storages$.createUnsafe(Storages.scala:43)
	at org.alephium.app.Server$Impl.<init>(Server.scala:122)
	at org.alephium.app.Server$.apply(Server.scala:106)
	at org.alephium.app.BootUp.<init>(Boot.scala:58)
	at org.alephium.app.Boot$.delayedEndpoint$org$alephium$app$Boot$1(Boot.scala:37)
	at org.alephium.app.Boot$delayedInit$body.apply(Boot.scala:35)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at org.alephium.app.Boot$.main(Boot.scala:35)
	at org.alephium.app.Boot.main(Boot.scala)
```

**Comment by polarker** [comment]
@suyanlong many thanks for the bug report. Which version of Java did you use ?

**Comment by suyanlong** [comment]
@polarker sorry, i forgot append java version。
```shell
root@DESKTOP-0QIGCLU:~/alephium# java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

**Comment by suyanlong** [comment]
@polarker yes, run Ubuntu of WSL on windows。

**Comment by polarker** [comment]
> @polarker yes, run Ubuntu of WSL on windows. i try other machine. thanks.

It should work if you upgrade your WSL to the latest version

**Comment by suyanlong** [comment]
similar rockdb exception issues [#5416](https://github.com/facebook/rocksdb/pull/5416)
