### ISSUE TITLE
New error alephium-1.2.5

### ISSUE THREAD

**Issue by altinsoft** [alephium/alephium#512]
[33m2022-01-26 00:46:02,091[0;39m [32m[-dispatcher-7][0;39m [31mWARN [0;39m [36mo.a.f.h.BlockChainHandler[0;39m              - Invalid block/header 000000000002a55787a20cd1722e0b7cf76ef5f233ab229976062f1ea0546160: InvalidTxsMerkleRoot : 65b384a0ba0e014aba0e014a889a2149cc2b195c97eb546d00070000000000225a5bac0aeeaa2498a4be659ff1b24f4a6410a8cbc29fc8ec39b500000000001a0f3ccd2ce168b7fcaa727dee870a8d7f8189bfac23e6032ca9ea000000000012f4e4ec256f0b5657969e09689285abfb1fc350f6e24362096eff00000000000e94a1bc987aa5575650a4bd2a9122b35f9831a9bd0c6d5a3bb98000000000000424c0ed387a24ad4b23bf43ff990e4f965fa5d18dc04991f6e32100000000001536a48c431442be1815029986a4146371b45aa750d66bad9a8e420000000000168910666c2578e41298cf648cba7cba279289bebc255a1d1674a30bb8d2a71ea2eb6434eb7d3563c0f58e7bd4c23244512300c78d844b910b0b7d777bbd5ff320602ee5712be6c23f397e24e15a29a9d1994ea4717dcec25bc51e0000017e95902adf1b2a83430100000080004e20bb9aca000001c42e52a1079f6371f8001ea5b1567f782a1001d95b308ed14374cfce19214ea8e6fe7e4c448eee4fc7d70000017e9759ef7e000a00000000017e95902bfe0100000000
[33m2022-01-26 00:46:02,091[0;39m [32m[-dispatcher-7][0;39m [31mWARN [0;39m [36mo.a.f.h.BlockChainHandler[0;39m              - Invalid block/header 000000000002a55787a20cd1722e0b7cf76ef5f233ab229976062f1ea0546160: InvalidTxsMerkleRoot : 65b384a0ba0e014aba0e014a889a2149cc2b195c97eb546d00070000000000225a5bac0aeeaa2498a4be659ff1b24f4a6410a8cbc29fc8ec39b500000000001a0f3ccd2ce168b7fcaa727dee870a8d7f8189bfac23e6032ca9ea000000000012f4e4ec256f0b5657969e09689285abfb1fc350f6e24362096eff00000000000e94a1bc987aa5575650a4bd2a9122b35f9831a9bd0c6d5a3bb98000000000000424c0ed387a24ad4b23bf43ff990e4f965fa5d18dc04991f6e32100000000001536a48c431442be1815029986a4146371b45aa750d66bad9a8e420000000000168910666c2578e41298cf648cba7cba279289bebc255a1d1674a30bb8d2a71ea2eb6434eb7d3563c0f58e7bd4c23244512300c78d844b910b0b7d777bbd5ff320602ee5712be6c23f397e24e15a29a9d1994ea4717dcec25bc51e0000017e95902adf1b2a83430100000080004e20bb9aca000001c42e52a1079f6371f8001ea5b1567f782a1001d95b308ed14374cfce19214ea8e6fe7e4c448eee4fc7d70000017e9759ef7e000a00000000017e95902bfe0100000000
[33m2022-01-26 05:03:13,102[0;39m [32m[ext-global-42][0;39m [31mWARN [0;39m [36mo.a.f.c.BlockChain$$anon$1[0;39m             - Update hashes order at: chainIndex ChainIndex(2, 1); height 92434
[33m2022-01-26 05:03:27,149[0;39m [32m[ext-global-42][0;39m [31mWARN [0;39m [36mo.a.f.c.BlockChain$$anon$1[0;39m             - Update hashes order at: chainIndex ChainIndex(3, 1); height 94794
[33m2022-01-26 11:39:02,318[0;39m [32m[-dispatcher-4][0;39m [1;31mERROR[0;39m [36mo.a.u.DefaultStrategy[0;39m                  - Unhandled throwable, resume the actor: java.lang.NullPointerException: Cannot invoke "org.alephium.protocol.model.BrokerInfo.address()" because "remoteBrokerInfo" is null
	at org.alephium.flow.network.sync.BlockFlowSynchronizer$$anonfun$handle$1.applyOrElse(BlockFlowSynchronizer.scala:71)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:244)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at org.alephium.flow.network.sync.BlockFlowSynchronizer.aroundReceive(BlockFlowSynchronizer.scala:50)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

[33m2022-01-26 11:39:02,318[0;39m [32m[-dispatcher-6][0;39m [31mWARN [0;39m [36ma.a.OneForOneStrategy[0;39m

**Comment by polarker** [comment]
duplicated issue. closing
