### ISSUE TITLE
alephium-2.5.0.jar crashes if `.alephium-wallets` folder is a soft link

### ISSUE THREAD

**Issue by blackmennewstyle** [alephium/alephium#959]
I have an issue on `GNU/Linux Debian 11` with `alephium-2.5.0.jar` if the `.alephium-wallets` folder is a soft link.
```
lrwxrwxrwx  1 ceedii ceedii   26 Aug 13 10:13 .alephium -> /mnt/common_data/.alephium
lrwxrwxrwx  1 ceedii ceedii   26 Aug 13 10:17 .alephium-wallets -> /mnt/common_data/.alephium-wallets
```
It has no issue with `.alephium` being a soft link however refuses to proceed with `.alephium-wallets`, here the content of `alephium-errors.log`
```
^[[33m2023-08-13 13:27:02,110^[[0;39m ^[[32m[ol-3-worker-3]^[[0;39m ^[[1;31mERROR^[[0;39m ^[[36mo.a.app.BootUp^[[0;39m                         - Fatal error during initialization: {}
java.nio.file.FileAlreadyExistsException: /home/ceedii/.alephium-wallets
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
        at java.base/java.nio.file.Files.createDirectory(Files.java:690)
        at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
        at java.base/java.nio.file.Files.createDirectories(Files.java:743)
        at org.alephium.wallet.service.WalletService$Impl.$anonfun$startSelfOnce$1(WalletService.scala:251)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.Try$.apply(Try.scala:210)
        at org.alephium.wallet.service.WalletService$Impl.startSelfOnce(WalletService.scala:251)
        at org.alephium.util.Service.$anonfun$start$2(Service.scala:47)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
I need to run in that configuration on my pool since my node databases and data run on a dedicated SSD.

**Comment by tdroxler** [comment]
We'll have a look why it doesn't work, but in the mean time you could also [change your configuration](https://github.com/alephium/alephium/blob/c92463579a404e29519c5ab4df511e1ea562a891/wallet/src/main/resources/application.conf#L6)
Try to add `wallet.secret-dir = "/mnt/common_data/.alephium-wallets"` into your `.alephium/user.conf`

**Comment by blackmennewstyle** [comment]
> We'll have a look why it doesn't work, but in the mean time you could also [change your configuration](https://github.com/alephium/alephium/blob/c92463579a404e29519c5ab4df511e1ea562a891/wallet/src/main/resources/application.conf#L6) Try to add `wallet.secret-dir = "/mnt/common_data/.alephium-wallets"` into your `.alephium/user.conf`

Thanks for the heads up, truly appreciated :+1:

**Comment by tdroxler** [comment]
@blackmennewstyle I could reproduce the issue and fix it in https://github.com/alephium/alephium/pull/961
